backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: http://firstsmmschool.ru
logo_url: /static/img/logo.svg
locale: 'ru'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: Блог
    name: blog
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - { label: "Содержимое", name: "body", widget: "markdown" }
      - widget: select
        label: "Теги"
        name: "tags"
        multiple: true
        create: true
        options: ["SMM", "Дизайн", "Веб"]
  - label: Таплинк
    name: taplink
    editor:
      preview: false
    files:
      - label: Ссылки
        name: items
        file: "src/_data/info.yaml"
        fields:
          - label: Список ссылок
            label_singular: ссылка
            name: items
            widget: list
            fields:
              - { label: Надпись на кнопке, name: text, widget: string }
              - { label: Ссылка, name: href, widget: string }
  - label: Основной сайт
    name: settings
    editor:
      preview: false
    files:
      - label: Навигация
        name: items
        file: "src/_data/navigation.yaml"
        fields:
          - label: Список ссылок
            label_singular: ссылка
            name: items
            widget: list
            fields:
              - { label: Заголовок, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: Курс
        name: course
        file: "src/_data/course.yaml"
        fields:
          - { label: Дата старта, name: date, widget: datetime, date_format: true, time_format: false}
          - { label: Стоимость курса, name: price, widget: number, step: 1000, value_type: "int", default: 30000 }
          - { label: Стоимость по скидке, name: discount, widget: number, step: 1000, value_type: "int", default: 25000, required: false }
          - { label: Номер телефона менеджера, name: tel, widget: string, hint: "+7 999 999-99-99" }
          - { label: Имя менеджера, name: name, widget: string }
          - { label: Подпись менеджера, name: job, widget: string }
          - { label: Фотография менеджера, name: src,  widget: image, allow_multiple: false }
          - { label: Почта школы, name: email, widget: string }
          - { label: Ссылка на ВКонтакте Школы, name: vk, widget: string, required: false }
          - { label: Ссылка на Инстаграм Школы, name: ig, widget: string, required: false }
      - label: Галерея
        name: gallery
        file: "src/_data/gallery.yaml"
        fields:
          - label: Галерея
            label_singular: фото
            name: items
            widget: list
            fields:
              - { label: Альтернативный текст, name: alt, widget: string }
              - { label: Фотография, name: src,  widget: image, allow_multiple: false }
      - label: Акции
        name: gallery
        file: "src/_data/sale.yaml"
        fields:
          - label: Акции
            label_singular: акция
            name: items
            widget: list
            fields:
              - { label: Альтернативный текст, name: alt, widget: string }
              - { label: Ссылка, name: url, widget: string }
              - { label: Картинка, name: src,  widget: image, allow_multiple: false }
      - label: Программа
        name: program
        file: "src/_data/program.yaml"
        fields:
          - { label: Описание, name: description, widget: text }
          - label: Блоки
            label_singular: блок
            name: blocks
            widget: list
            collapsed: false
            fields:
              - { label: Название, name: heading, widget: string }
              - { label: ID, name: id, widget: string, hint: "Английское слово маленькими буквами, например marketing или design" }
              - { label: Продолжительность, name: duration, widget: string, required: false }
              - { label: Подпись, name: description, widget: string, required: false }
              - label: Описание
                label_singular: параграф
                name: text
                widget: list
                fields:
                  - { label: Параграф, name: paragraph, widget: text }
              - label: Инструменты
                label_singular: инструмент
                name: instruments
                widget: list
                fields:
                  - { label: Название, name: label, widget: string }
              - label: Преподаватели
                label_singular: преподаватель
                name: teachers
                widget: list
                fields:
                  - { label: Имя учителя, name: name, widget: string }
                  - { label: Регалии учителя, name: job, widget: string, required: false }
                  - { label: Фотография учителя, name: src,  widget: image, allow_multiple: false, required: false }
      - label: Отзывы
        name: feedback
        file: "src/_data/feedback.yaml"
        fields:
          - label: Отзывы
            label_singular: отзыв
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Имя, name: name, widget: string }
              - { label: Фотография, name: src,  widget: image, allow_multiple: false }
              - { label: 'Место работы', name: work, widget: string, required: false }
              - { label: 'Ссылка на работу', name: workurl, widget: string, required: false }
              - { label: Отзыв, name: text, widget: text }
              - { label: 'Ссылка на отзыв целиком', name: url, widget: string }
          - label: Клиенты
            label_singular: логотип
            name: clients
            widget: list
            fields:
              - { label: Название, name: alt, widget: string }
              - { label: Логотип, name: src,  widget: image, allow_multiple: false }
      - label: Партнёры
        name: partners
        file: "src/_data/partners.yaml"
        fields:
          - label: Партнёры
            name: items
            widget: list
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Описание, name: description, widget: text }
              - { label: URL, name: href, widget: string }
              - { label: Логотип, name: url,  widget: image, allow_multiple: false }