backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://перваяшколасмм.рф
locale: 'ru'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Настройка"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Навигация"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            fields:
              - { label: Заголовок, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Программа"
        name: "program"
        file: "src/_data/program.yaml"
        fields:
          - { label: Описание, name: description, widget: text }
          - label: Блоки
            label_singular: блок
            name: blocks
            widget: list
            collapsed: false
            fields:
              - { label: Название, name: heading, widget: string }
              - { label: ID, name: id, widget: string, hint: "Английское слово маленькими буквами, например marketing или design" }
              - { label: Продолжительность, name: duration, widget: string, required: false }
              - { label: Подпись, name: description, widget: string, required: false }
              - { label: Описание, name: text, widget: text }
              - label: Инструменты
                label_singular: инструмент
                name: instruments
                widget: list
                fields:
                  - { label: Название, name: label, widget: string }
              - { label: Имя учителя, name: name, widget: string, required: false }
              - { label: Регалии учителя, name: job, widget: string, required: false }
              - { label: Фотография учителя, name: src,  widget: image, allow_multiple: false, required: false }
      - label: "Отзывы"
        name: "feedback"
        file: "src/_data/feedback.yaml"
        fields:
          - label: Отзывы
            label_singular: отзыв
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Имя, name: name, widget: string }
              - { label: Фотография, name: src,  widget: image, allow_multiple: false }
              - { label: 'Место работы', name: work, widget: string, required: false }
              - { label: 'Ссылка на работу', name: workurl, widget: string, required: false }
              - { label: Отзыв, name: text, widget: text }
              - { label: 'Ссылка на отзыв целиком', name: url, widget: string }
          - label: Клиенты
            label_singular: логотип
            name: clients
            widget: list
            fields:
              - { label: Название, name: alt, widget: string }
              - { label: Логотип, name: src,  widget: image, allow_multiple: false }
      - label: Курс
        name: "course"
        file: "src/_data/course.yaml"
        fields:
          - { label: Дата старта, name: date, widget: datetime, date_format: true, time_format: false}
          - { label: Стоимость курса, name: price, widget: number, step: 1000, value_type: "int", default: 30000 }
          - { label: Стоимость по скидке, name: discount, widget: number, step: 1000, value_type: "int", default: 25000, required: false }
      - label: "Партнёры"
        name: "partners"
        file: "src/_data/partners.yaml"
        fields:
          - label: Партнёры
            name: items
            widget: list
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Описание, name: description, widget: text }
              - { label: URL, name: href, widget: string }
              - { label: Логотип, name: url,  widget: image, allow_multiple: false }